@startuml

skinparam packageStyle rect
left to right direction

together {
:Исполнитель:
:Менеджер:
:HR-отдел:
:Системный администратор:
}


:Исполнитель: --> (Система учета рабочего времени) : Фиксирует рабочее время
:Менеджер: --> (Система учета рабочего времени) : Контролирует задачи и время сотрудников
:HR-отдел: --> (Система учета рабочего времени) : Получает данные для расчета зарплаты и учета занятости
:Системный администратор: --> (Система учета рабочего времени) : Настраивает и поддерживает систему

together {
:Система управления проектами:
:Бухгалтерская система:
:HR-система:
}

(Система учета рабочего времени) --> :Система управления проектами: : Синхронизирует задачи и проекты
(Система учета рабочего времени) --> :Бухгалтерская система: : Передает данные для расчета зарплаты
(Система учета рабочего времени) --> :HR-система: : Передает данные о занятости и отпусках

@enduml
